name: Deploy to projects.brianwalker.dev
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build project
        run: npm install && npm run build
      - name: Deploy to hub
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: brianwalkerdev/projects.brianwalker.dev
          publish_branch: main
          publish_dir: ./dist
          destination_dir: responsive-personal-portfolio-website
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
